### ISSUE TITLE
Unable to Build the OLOidc binary to create the framework

### ISSUE THREAD

**Issue by roy-ml** [onelogin/onelogin-oidc-ios#12]
we also tried generate xcframework that include both arm64 iOS and iPhone stimulator. However we still face issue when trying to run our codebase after included it.

Code we used to generated the xcframework:
`xcodebuild archive \
-scheme OLOidc \
-configuration Release \
-destination 'generic/platform=iOS' \
-archivePath './build/OLOidc.framework-iphoneos.xcarchive' \
SKIP_INSTALL=NO \
BUILD_LIBRARIES_FOR_DISTRIBUTION=YES`

`xcodebuild archive \
-scheme OLOidc \
-configuration Release \
-destination 'generic/platform=iOS Simulator' \
-archivePath './build/OLOidc.framework-iphonesimulator.xcarchive' \
SKIP_INSTALL=NO \
BUILD_LIBRARIES_FOR_DISTRIBUTION=YES`

`xcodebuild -create-xcframework \
-framework './build/OLOidc.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/OLOidc.framework' \
-framework './build/OLOidc.framework-iphoneos.xcarchive/Products/Library/Frameworks/OLOidc.framework' \
-output './build/OLOidc.xcframework'`

Error we faced:
`/Users/xloi/Library/Developer/Xcode/DerivedData/MoneyLion-gxbudjzmwfkbipgokiieeclrorpr/Build/Products/Debug-iphonesimulator/OLOidc.framework/Modules/OLOidc.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:52:59: 'OLOidcError' is not a member type of class 'OLOidc.OLOidc'`

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/101554839/162710432-d9fbd9b3-8d6a-46b3-99ba-ed64d94dd02e.png">

**Comment by roy-ml** [comment]
I did try to compile with arm64 target, and the archive successed.

However, after import the framework (in framework and build phase), our code base won't build and showing the errors:


`/Users/xxx/Project/mobile-app/ios/OneLoginTranslationLayer.swift:11:8: Could not find module 'OLOidc' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios, at: /Users/xxx/Project/mobile-app/ios/OLOidc.framework/Modules/OLOidc.swiftmodule`


Any idea on this?

**Comment by roy-ml** [comment]
we also tried generate xcframework that include both arm64 iOS and iPhone stimulator. However we still face issue when trying to run our codebase after included it.

Code we used to generated the xcframework:
`xcodebuild archive \
-scheme OLOidc \
-configuration Release \
-destination 'generic/platform=iOS' \
-archivePath './build/OLOidc.framework-iphoneos.xcarchive' \
SKIP_INSTALL=NO \
BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

xcodebuild archive \
-scheme OLOidc \
-configuration Release \
-destination 'generic/platform=iOS Simulator' \
-archivePath './build/OLOidc.framework-iphonesimulator.xcarchive' \
SKIP_INSTALL=NO \
BUILD_LIBRARIES_FOR_DISTRIBUTION=YES



xcodebuild -create-xcframework \
-framework './build/OLOidc.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/OLOidc.framework' \
-framework './build/OLOidc.framework-iphoneos.xcarchive/Products/Library/Frameworks/OLOidc.framework' \
-output './build/OLOidc.xcframework'`

Error we faced:
`/Users/xloi/Library/Developer/Xcode/DerivedData/MoneyLion-gxbudjzmwfkbipgokiieeclrorpr/Build/Products/Debug-iphonesimulator/OLOidc.framework/Modules/OLOidc.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:52:59: 'OLOidcError' is not a member type of class 'OLOidc.OLOidc'`

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/101554839/162710432-d9fbd9b3-8d6a-46b3-99ba-ed64d94dd02e.png">

**Comment by roy-ml** [comment]
We dig into it and found that this issue is related to the naming of the framework. Apparently there is a limitation/bug in swift that if you have a type and a framework with the same name, the name is always assumed to refer to the type.

`Public class 'OLOidc.OLOidc' shadows module 'OLOidc', which may cause failures when importing 'OLOidc' or its clients in some configurations; please rename either the class 'OLOidc.OLOidc' or the module 'OLOidc', or see https://bugs.swift.org/browse/SR-14195 for workarounds`

![image](https://user-images.githubusercontent.com/101554839/163129586-a0eedcf4-5b11-4227-9972-4d60b3d8b15d.png)

For more informations regarding to the issue:
https://bugs.swift.org/browse/SR-14195
https://forums.swift.org/t/frameworkname-is-not-a-member-type-of-frameworkname-errors-inside-swiftinterface/28962

**Comment by Nawshad-OneLogin** [comment]
Hi Roy,

Can you try this:

Run the following script:
find . -name "*.swiftinterface" -exec sed -i -e 's/OLOidc\.//g' {​​​​​​​}​​​​​​​ \;

**Comment by roy-ml** [comment]
Hi Nawshad,

The given script will remove all the text 'OLOidc' in swiftinterface right?

This caused the issue `'OLOidc' is unavailable: cannot find Swift declaration for this class`

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/101554839/164148256-5fc5acbd-a467-4c41-a1a2-6eff1a1099d2.png">

**Comment by roy-ml** [comment]
Hi Nawshad,

I am using the following script instead:
`find . -name "*.swiftinterface" -exec sed -i '' 's/OLOidc\.//g' '{}' +`

And it is working fine now, thanks for the help.
